version: '2'

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ../volumes/certs:/etc/nginx/certs:ro

  generator:
    container_name: ${COMPOSE_PROJECT_NAME}_generator
    image: jwilder/docker-gen
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../volumes/proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    entrypoint: /usr/local/bin/docker-gen -notify-sighup ${COMPOSE_PROJECT_NAME}_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    container_name: ${COMPOSE_PROJECT_NAME}_letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../volumes/certs:/etc/nginx/certs:rw
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${COMPOSE_PROJECT_NAME}_generator
