version: '3.2'

networks:
  proxy:
    external:
      name: proxy_network

services:
  nginx:
    container_name: proxy_nginx
    image: nginx
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ../etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ../volumes/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ../volumes/vhost.d
        target: /etc/nginx/vhost.d
      - type: bind
        source: ../volumes/html
        target: /usr/share/nginx/html
      - type: bind
        source: ../volumes/certs
        target: /etc/nginx/certs
        read_only: true
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://${SYSLOG_HOST}:${SYSLOG_PORT}"
        tag: "{{.DaemonName}}/{{.Name}}"

  generator:
    container_name: proxy_generator
    image: jwilder/docker-gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup proxy_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - type: bind
        source: ../volumes/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ../volumes/vhost.d
        target: /etc/nginx/vhost.d
      - type: bind
        source: ../volumes/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: ../etc/nginx/nginx.tmpl
        target: /etc/docker-gen/templates/nginx.tmpl
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  letsencrypt:
    container_name: proxy_letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    environment:
      NGINX_PROXY_CONTAINER: proxy_nginx
      NGINX_DOCKER_GEN_CONTAINER: proxy_generator
      REUSE_ACCOUNT_KEYS: true
      REUSE_PRIVATE_KEYS: true
    networks:
      - proxy
    volumes:
      - type: bind
        source: ../volumes/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ../volumes/vhost.d
        target: /etc/nginx/vhost.d
      - type: bind
        source: ../volumes/html
        target: /usr/share/nginx/html
      - type: bind
        source: ../volumes/certs
        target: /etc/nginx/certs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
