version: '2'

networks:
  proxy:
    external:
      name: "proxy-network"

services:
  nginx:
    container_name: proxy_nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ../volumes/certs:/etc/nginx/certs:ro
    networks:
      - proxy
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  generator:
    container_name: proxy_generator
    image: jwilder/docker-gen
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../volumes/proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup proxy_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  letsencrypt:
    container_name: proxy_letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../volumes/certs:/etc/nginx/certs:rw
    networks:
      - proxy
    environment:
      NGINX_DOCKER_GEN_CONTAINER: proxy_generator
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
