version: '2.2'

networks:
  proxy:
    external:
      name: proxy_network

services:
  nginx:
    container_name: proxy_nginx
    image: nginx:stable-alpine
    restart: always
    cpus: 0.1
    mem_limit: 16M
    depends_on:
      - generator
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../volumes/conf.d:/etc/nginx/conf.d:rw
      - ../volumes/vhost.d:/etc/nginx/vhost.d:rw
      - ../volumes/html:/usr/share/nginx/html:rw
      - ../volumes/certs:/etc/nginx/certs:ro
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
#      driver: syslog
#      options:
#        syslog-address: "tcp://${SYSLOG_HOST}:${SYSLOG_PORT}"
#        tag: "{{.DaemonName}}/{{.Name}}"

  generator:
    container_name: proxy_generator
    image: jwilder/docker-gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup proxy_nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always
    cpus: 0.1
    mem_limit: 16M
    depends_on:
      - letsencrypt
    networks:
      - proxy
    volumes:
      - ../volumes/conf.d:/etc/nginx/conf.d:rw
      - ../volumes/vhost.d:/etc/nginx/vhost.d:rw
      - ../volumes/certs:/etc/nginx/certs:ro
      - ../etc/nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  letsencrypt:
    container_name: proxy_letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    cpus: 0.1
    mem_limit: 64M
    environment:
      NGINX_PROXY_CONTAINER: proxy_nginx
      NGINX_DOCKER_GEN_CONTAINER: proxy_generator
      REUSE_ACCOUNT_KEYS: 1
      REUSE_PRIVATE_KEYS: 1
    networks:
      - proxy
    volumes:
      - ../volumes/conf.d:/etc/nginx/conf.d:rw
      - ../volumes/vhost.d:/etc/nginx/vhost.d:rw
      - ../volumes/html:/usr/share/nginx/html:rw
      - ../volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
