version: '2'

services:
  registry_web:
    container_name: ${COMPOSE_PROJECT_NAME}_registry_web
    image: nginx
    restart: always
    environment:
      VIRTUAL_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_EMAIL: ${REGISTRY_EMAIL}

  registry:
    container_name: ${COMPOSE_PROJECT_NAME}_registry
    image: registry:2
    restart: always
    ports:
      - ${REGISTRY_PORT}:5000
    volumes:
      - ../volumes/registry:/var/lib/registry
      - ../volumes/certs:/certs:ro
      - ../volumes/auth:/auth:ro
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: ${REGISTRY_SECRET}
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${REGISTRY_HOST}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/${REGISTRY_HOST}/key.pem
