version: '3'

networks:
  registry:
    external:
      name: registry_network

services:
  registry_web:
    container_name: registry_web
    image: nginx
    restart: unless-stopped
    networks:
      - registry
    volumes:
      - ../volumes/web:/usr/share/nginx/html:ro
    environment:
      VIRTUAL_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_EMAIL: ${REGISTRY_EMAIL}
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  registry:
    container_name: registry_registry
    image: registry:2
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: ${REGISTRY_SECRET}
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${REGISTRY_HOST}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/${REGISTRY_HOST}/key.pem
    networks:
      - registry
    ports:
      - "${REGISTRY_PORT}:5000"
    volumes:
      - ../volumes/registry:/var/lib/registry
      - ../volumes/certs:/certs:ro
      - ../volumes/auth:/auth:ro
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
