version: '3.2'

networks:
  registry:
    external:
      name: registry_network

services:
  registry_web:
    container_name: registry_web
    image: nginx
    restart: unless-stopped
    networks:
      - registry
    volumes:
      - type: bind
        source: ../web/registry
        target: /usr/share/nginx/html
        read_only: true
    environment:
      VIRTUAL_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_HOST: ${REGISTRY_HOST}
      LETSENCRYPT_EMAIL: ${REGISTRY_EMAIL}
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }

  registry:
    container_name: registry_registry
    image: registry:2.5.2
    restart: unless-stopped
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_SECRET: ${REGISTRY_SECRET}
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/${REGISTRY_HOST}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/${REGISTRY_HOST}/key.pem
    networks:
      - registry
    ports:
      - "${REGISTRY_PORT}:5000"
    volumes:
      - type: bind
        source: ../volumes/registry
        target: /var/lib/registry
      - type: bind
        source: ../volumes/certs
        target: /certs
        read_only: true
      - type: bind
        source: ../volumes/auth
        target: /auth
        read_only: true
    logging:
      driver: "json-file"
      options: { max-size: "1m", max-file: "3" }
